-- User Profile and Activity Schema
-- Run this in Supabase SQL Editor

-- 1. Profiles table for persistent game state
CREATE TABLE IF NOT EXISTS user_profiles (
  tg_uid text PRIMARY KEY,
  streak_days int DEFAULT 0,
  last_active_date date DEFAULT CURRENT_DATE,
  boss_hp int DEFAULT 100,
  total_xp int DEFAULT 0,
  created_at timestamp with time zone DEFAULT NOW()
);

-- 2. Daily Activity Log for Weekly Chart
CREATE TABLE IF NOT EXISTS user_daily_activity (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tg_uid text NOT NULL,
  activity_date date DEFAULT CURRENT_DATE,
  words_learned int DEFAULT 0,
  xp_earned int DEFAULT 0,
  UNIQUE(tg_uid, activity_date)
);

-- 3. Update word stats table (if not exists column)
-- We need to track consecutive correct answers for the "3x rule"
ALTER TABLE user_word_stats ADD COLUMN IF NOT EXISTS consecutive_correct int DEFAULT 0;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_activity_uid_date ON user_daily_activity(tg_uid, activity_date);

-- RLS Policies (Simple/Open for prototype with known users)
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_daily_activity ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all profiles" ON user_profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all activity" ON user_daily_activity FOR ALL USING (true) WITH CHECK (true);
